// src/pages/city/index.jsx
//about.js
import React from 'react';
import './index.css';
import { searchplace} from '../../service/index.js';
import {getStore, setStore, removeStore} from '../../config/mUtils'
import Header from '../../components/header/index.jsx';
import createHistory from 'history/createBrowserHistory';
export default class City extends React.Component {
  constructor(props) {
      super(props);
      this.state = {
        inputVaule:'', // 搜索地址
        cityid:'', // 当前城市id
        cityname:'', // 当前城市名字
        placelist:[], // 搜索城市列表
        placeHistory:[], // 历史搜索记录
        historytitle: true, // 默认显示搜索历史头部，点击搜索后隐藏
        placeNone: false, // 搜索无结果，显示提示信息
      }
  }
  clearAll(){ //清除历史搜索记录
    removeStore('placeHistory');
    this.initData();
  }
  
  initData(){ //初始化所选择的城市，如果没有默认深圳 初始化搜索历史记录
    if(this.props.location.state){
      this.setState({
        cityid:this.props.location.state.id,
        cityname:this.props.location.state.name
      })
    }else{
      this.setState({
        cityid: 11,
        cityname:'深圳'
      })
    }
    //获取本地查询记录
    if (getStore('placeHistory')) {
      this.setState({
        placelist:JSON.parse(getStore('placeHistory'))
      })
    }else{
      this.setState({
        placelist:[]
      })
    } 
  }
  inptChange(event){
    this.setState({
      inputVaule:event.target.value
    })
  }
  componentDidMount() {
    this.initData()
  }
  //发送搜索信息inputVaule
  postpois(){
      //输入值不为空时才发送信息
      if (this.state.inputVaule) {
          searchplace(this.state.cityid, this.state.inputVaule).then(res => {
            this.setState({
              historytitle:false,
              placelist:res,
              placeNone:res.length? false : true
            })
          })
      }
  }
  nextpage(index,geohash){
    let history = getStore('placeHistory');
    let choosePlace = this.state.placelist[index];
    let  placeHistory = []
    if (history) { //
        let checkrepeat = false;
        placeHistory = JSON.parse(history)
        placeHistory.forEach(item => {
            if (item.geohash === geohash) {
                checkrepeat = true;
            }
        })
        if (!checkrepeat) {
          placeHistory.push(choosePlace)
        }
    }else {
        placeHistory.push(choosePlace)
    }
    setStore('placeHistory',placeHistory)
    // this.props.history.push({pathname:'/msite', query:{geohash}});
    // let history1 = createHistory(); //创建历史对象
    // history1.push('/msite', { some:geohash })
  }
  render() {
    return (
		<div className="city_container">
          <Header goback>
            {this.state.cityname}
          </Header>
		      <section className="city_form">
            <div>
                <input type="search" onChange={e => this.inptChange(e)} value={this.state.inputVaule}   name="city" placeholder="输入学校、商务楼、地址" className="city_input input_style"  />
            </div>
            <div>
                <button  className="city_submit input_style" onClick={this.postpois.bind(this)}>提交</button>
            </div>
          </section>
          <ul className="getpois_ul">
            {this.state.placelist.map((item,i)=>{
              return (
                <li key={i} onClick={this.nextpage(i,item.geohash)}>
                   <h4 className="pois_name ellipsis">{item.name}</h4>
                   <p className="pois_address ellipsis">{item.address}</p>
                </li>
              )
            })}
          </ul>
          {
            this.state.placeNone?<div className="search_none_place">抱歉！无搜索结果</div>:''
          }
          {
           this.state.placelist.length? <footer v-if="" className="clear_all_history" onClick={this.clearAll}>清空所有</footer>:''
          }
		</div>
	)
  }
}

// src/pages/city/city.vue
<template>
  	<div class="city_container">
        <head-top :head-title="cityname" go-back='true'>
            <router-link to="/home" slot="changecity" class="change_city">切换城市</router-link>
        </head-top>
        <form class="city_form" v-on:submit.prevent>
            <div>
                <input type="search" name="city" placeholder="输入学校、商务楼、地址" class="city_input input_style" required v-model='inputVaule'>
            </div>
            <div>
                <input type="submit" name="submit" class="city_submit input_style" @click='postpois' value="提交">
            </div>
        </form>
        <header v-if="historytitle" class="pois_search_history">搜索历史</header>
        <ul class="getpois_ul">
            <li v-for="(item, index) in placelist" @click='nextpage(index, item.geohash)' :key="index">
                <h4 class="pois_name ellipsis">{{item.name}}</h4>
                <p class="pois_address ellipsis">{{item.address}}</p>
            </li>
        </ul>
        <footer v-if="historytitle&&placelist.length" class="clear_all_history" @click="clearAll">清空所有</footer>
        <div class="search_none_place" v-if="placeNone">很抱歉！无搜索结果</div>
    </div>
</template>

<script>
    import headTop from 'src/components/header/head'
    import {currentcity, searchplace} from 'src/service/getData'
    import {getStore, setStore, removeStore} from 'src/config/mUtils'

    export default {
    	data(){
            return{
                inputVaule:'', // 搜索地址
                cityid:'', // 当前城市id
                cityname:'', // 当前城市名字
                placelist:[], // 搜索城市列表
                placeHistory:[], // 历史搜索记录
                historytitle: true, // 默认显示搜索历史头部，点击搜索后隐藏
                placeNone: false, // 搜索无结果，显示提示信息
            }
        },

        mounted(){
            this.cityid = this.$route.params.cityid;
            //获取当前城市名字
            currentcity(this.cityid).then(res => {
                this.cityname = res.name;
            })
            this.initData();
        },

        components:{
            headTop
        },

        computed:{

        },

        methods:{
            initData(){
                //获取搜索历史记录
                if (getStore('placeHistory')) {
                    this.placelist = JSON.parse(getStore('placeHistory'));
                }else{
                    this.placelist = [];
                }
            },
            //发送搜索信息inputVaule
            postpois(){
                //输入值不为空时才发送信息
                if (this.inputVaule) {
                    searchplace(this.cityid, this.inputVaule).then(res => {
                        this.historytitle = false;
                        this.placelist = res;
                        this.placeNone = res.length? false : true;
                    })
                }
            },
            /**
             * 点击搜索结果进入下一页面时进行判断是否已经有一样的历史记录
             * 如果没有则新增，如果有则不做重复储存，判断完成后进入下一页
             */
            nextpage(index, geohash){
                let history = getStore('placeHistory');
                let choosePlace = this.placelist[index];
                if (history) {
                    let checkrepeat = false;
                    this.placeHistory = JSON.parse(history);
                    this.placeHistory.forEach(item => {
                        if (item.geohash == geohash) {
                            checkrepeat = true;
                        }
                    })
                    if (!checkrepeat) {
                        this.placeHistory.push(choosePlace)
                    }
                }else {
                    this.placeHistory.push(choosePlace)
                }
                setStore('placeHistory',this.placeHistory)
                this.$router.push({path:'/msite', query:{geohash}})
            },
            clearAll(){
                removeStore('placeHistory');
                this.initData();
            }
        }
    }

</script>
